
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umwgusdopzwvfqbkwapk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtd2d1c2RvcHp3dmZxYmt3YXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzEwMTEsImV4cCI6MjA2NzU0NzAxMX0.4dbBdknWvzi_GCZubowaLivFGWY4Fp-T-wKMnTYLzlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
